car_rental/config/routes.rb
Rails.application.routes.draw do


  resources :total_rentals
  get 'manage_statistics/total_stat'
  get 'manage_statistics/car_stat'
  root 'welcome#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  get 'saved', to: 'users#my_saved'
  post 'save_car', to: 'users#add_cars_to_favourite'

#  post 'rent_car', to: 'users#add_cars_to_rent'

  get 'rented', to: 'users#my_rented'
  get 'rent_car', to: 'users#add_cars_to_rent'

  delete 'delete', to: 'rented_cars#admin_destroy'

  get 'search', to: 'cars#search'

  post 'rented_cars/new'

  get 'about', to: "welcome#about"
  get 'services', to: "welcome#services"
  get 'contact', to: "welcome#contact"
  get 'blog', to: "welcome#blog"
  get 'fqa', to: "welcome#fqa"
  # get 'rented', to: 'users#my_rented'

  resources :cars do
    resources :reviews
  end
  resources :rented_cars
  resources :users
  resources :saved_cars

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

car_rental/app/models/user.rb
class User < ApplicationRecord
  has_many :saved_cars, dependent: :destroy
  has_many :savedcars, through: :saved_cars
  has_many :rented_cars, dependent: :destroy
  has_many :total_rentals
  # has_many :cars, through: :rented_cars
  # has_many :rentedcars, through: :rented_cars
#  has_many :rentals, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :user_name, presence: true, length: {minimum: 3, maximum: 25}, uniqueness: {case_sensitive: false}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
						uniqueness: {case_sensitive: false}, length: {minimum: 5, maximum: 50},
						format: {with: VALID_EMAIL_REGEX}
	has_secure_password

  validates :age, presence: true, numericality: {greater_than: 17 }
  validates :name, presence: true, length: {maximum: 25, minimum: 3}
  validates :address, presence: true, length: { minimum: 5}
  validates :points, numericality: {greater_than: -1 }



  def car_not_saved?(car_id)
    # if count is < 1 means that the count is zero so it isn't saved
    saved_cars.where(savedcar_id: car_id).count < 1
  end

  def car_not_rented?(car_id)
    # if count is < 1 means that the count is zero so it isn't saved
    rented_cars.where(car_id: car_id).count < 1
  end

end

car_rental/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy, :show]
  before_action :require_admin, only: [:destroy, :index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id

        format.html { redirect_to cars_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def my_saved
    @saved_cars = current_user.savedcars
  end


  # this method handles the user favourite
  def add_cars_to_favourite

    @car = User.find(params[:savedcar])
    current_user.saved_cars.build(savedcar_id: @car.id)

    if current_user.save
      flash[:notice] = 'car was successfully added'
    else
      flash[:danger] = 'There was something wrong with the car saving'
    end
    # redirect to the same page
    redirect_back(fallback_location:"/")
  end

  def my_rented
    @rented_cars = current_user.rented_cars
  end

  def add_cars_to_rent
    #@rented_cars = RentedCar.where(user_id: current_user.id).first
    @rented_cars = current_user.rented_cars
      #logger.info "size: #{@rented_cars.length}"

  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to cars_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_name, :password, :email, :name, :address, :dob, :age, :points, :admin)
    end

  def require_same_user
    if current_user != @user and !current_user.admin?
      #flash[:danger] = 'You can only edit your own account'
      redirect_to root_path
    end
  end

  # this will prevent the non admin users from having access to destroy action
  def require_admin
    if logged_in? and !current_user.admin?
      #flash[:danger] = 'Only admin users can perform that action'
      redirect_to root_path
    end
  end
end

car_rental/app/helpers/users_helper.rb
module UsersHelper
end

car_rental/app/views/users/add_cars_to_rent.html.erb
<body class="loader-active">
<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Rents</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Car List Area Start ==-->
<section id="car-list-area" class="section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <% if @rented_cars.size > 0 %>
          <% @rented_cars.each do |rent| %>
            <% car = Car.find(rent.car_id) %>
            <div class="row">
              <!-- Car List Content Start -->

              <div class="car-list-content">
                <!-- Single Car Start -->
                <div class="single-car-wrap">

                  <div class="row">
                    <!-- Single Car Thumbnail -->
                    <div class="col-lg-5">
                      <div class="car-list-thumb">
                        <!--car image-->
                        <% if car.image.attached? %>
                          <%= link_to image_tag(car.image), car_path(car) %>
                        <% end %>
                      </div>
                    </div>
                    <!-- Single Car Thumbnail -->

                    <!-- Single Car Info -->
                    <div class="col-lg-7">
                      <div class="display-table">
                        <div class="display-table-cell">
                          <div class="car-list-info">

                            <div class="row">
                              <div class="col-sm-8">
                                <h3><%= car.model %></h3>
                              </div>
                              <div class="col-sm-4">
                                <p class="rating">
                                  <% car.calculate_car_rate(car.id) %>
                                <div class="star-rating" data-score=<%= car.rank.ceil %>></div>
                                </p>
                              </div>
                            </div>
                            <h5><%= car.rent %>$ Rent /per a day</h5>
                            <p><%= car.discription %></p>
                            <ul class="car-info-list">
                              <li>Air Condition</li>
                              <li>From: <%= rent.rent_from_date %></li>
                              <li>To: <%= rent.rent_to_date %></li>
                            </ul>
                            <!--to delete the recipe from the saved-->
                            <%= link_to 'Edit', edit_rented_car_path(:id =>rent.id), class: "rent-btn" %>
                            <%#= link_to "Cancel", rent, method: :delete, class: "rent-btn" %>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- Single Car info -->
                  </div>
                </div>
                <!-- Single Car End -->
              </div>

              <!-- Car List Content End -->
            </div>
            <br>
          <% end %>
          </div>
          <!-- Sidebar Area Start -->
          <div class="col-lg-4">
            <div class="sidebar-content-wrap m-t-50">
              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>For More Informations</h3>

                <div class="sidebar-body">
                  <p><i class="fa fa-mobile"></i> +8801816 277 243</p>
                  <p><i class="fa fa-clock-o"></i> Mon - Sat 8.00 - 18.00</p>
                </div>
              </div>
              <!-- Single Sidebar End -->

              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>Rental Tips</h3>

                <div class="sidebar-body">
                  <ul class="recent-tips">
                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service1-img.png", alt: "JSOFT") %></a>
                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>

                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service2-img.png", alt: "JSOFT") %></a>

                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>
                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- Single Sidebar End -->

              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>Connect with Us</h3>

                <div class="sidebar-body">
                  <div class="social-icons text-center">
                    <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-behance"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-dribbble"></i></a>
                  </div>
                </div>
              </div>
              <!-- Single Sidebar End -->
            </div>
          </div>
          <!-- Sidebar Area End -->
          </div>

          </div>
          </section>
          <!--== Car List Area End ==-->


        <% else %>

          <section id="page-404-wrap" class="section-padding overlay">
            <div class="container">
              <div class="row">

                <div class="col-lg-12 text-center">
                  <div class="page-404-content">
                    <div class="number">
                      <div class="four">F</div>
                      <div class="zero">
                        <%= image_tag("404.png", alt: "JSOFT") %>
                      </div>
                      <div class="four">V</div>
                    </div>
                    <h4>NO CARS !</h4>
                    <p>SORRY, YOU DON'T HAVE CARS IN RENT <br> PLEASE, RENT SOME.</p>
                    <%= link_to ' Go to Home', root_path, class: "fa fa-home btn-404-home" %>
                  </div>
                </div>
              </div>
            </div>
          </section>

        <% end %>
        </body>



<script>
    $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        }
    });
</script>

car_rental/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Password</th>
      <th>Email</th>
      <th>Name</th>
      <th>Address</th>
      <th>Dob</th>
      <th>Age</th>
      <th>Points</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= user.dob %></td>
        <td><%= user.age %></td>
        <td><%= user.points %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

car_rental/app/views/users/my_rented.html.erb
<body class="loader-active">
<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Rents</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Car List Area Start ==-->
<section id="car-list-area" class="section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <% if @rented_cars.size > 0 %>
          <% @rented_cars.each do |car| %>
            <div class="row">
              <!-- Car List Content Start -->

              <div class="car-list-content">
                <!-- Single Car Start -->
                <div class="single-car-wrap">

                  <div class="row">
                    <!-- Single Car Thumbnail -->
                    <div class="col-lg-5">
                      <div class="car-list-thumb">
                        <!--car image-->
                        <% if car.image.attached? %>
                          <%= link_to image_tag(car.image), car_path(car) %>
                        <% end %>
                      </div>
                    </div>
                    <!-- Single Car Thumbnail -->

                    <!-- Single Car Info -->
                    <div class="col-lg-7">
                      <div class="display-table">
                        <div class="display-table-cell">
                          <div class="car-list-info">

                            <h2> <%= car.model %></h2>
                            <h5><%= car.rent %>$ Rent /per a day</h5>
                            <p><%= car.discription %></p>
                            <ul class="car-info-list">
                              <li>Air Condition</li>
                              <li>Diesel</li>
                              <li>Auto</li>
                            </ul>

                            <p class="rating">

                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star unmark"></i>
                            </p>
                            <!--to delete the recipe from the saved-->
                            <%= link_to "Cancel", rented_car_path(car), method: :delete, class: "rent-btn" %>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- Single Car info -->
                  </div>
                </div>
                <!-- Single Car End -->
              </div>

              <!-- Car List Content End -->
            </div>
            <br>
          <% end %>
          </div>
          <!-- Sidebar Area Start -->
          <div class="col-lg-4">
            <div class="sidebar-content-wrap m-t-50">
              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>For More Informations</h3>

                <div class="sidebar-body">
                  <p><i class="fa fa-mobile"></i> +8801816 277 243</p>
                  <p><i class="fa fa-clock-o"></i> Mon - Sat 8.00 - 18.00</p>
                </div>
              </div>
              <!-- Single Sidebar End -->

              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>Rental Tips</h3>

                <div class="sidebar-body">
                  <ul class="recent-tips">
                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service1-img.png", alt: "JSOFT") %></a>
                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>

                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service2-img.png", alt: "JSOFT") %></a>

                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>
                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- Single Sidebar End -->

              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>Connect with Us</h3>

                <div class="sidebar-body">
                  <div class="social-icons text-center">
                    <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-behance"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-dribbble"></i></a>
                  </div>
                </div>
              </div>
              <!-- Single Sidebar End -->
            </div>
          </div>
          <!-- Sidebar Area End -->
          </div>

          </div>
          </section>
          <!--== Car List Area End ==-->


        <% else %>

          <section id="page-404-wrap" class="section-padding overlay">
            <div class="container">
              <div class="row">

                <div class="col-lg-12 text-center">
                  <div class="page-404-content">
                    <div class="number">
                      <div class="four">F</div>
                      <div class="zero">
                        <%= image_tag("404.png", alt: "JSOFT") %>
                      </div>
                      <div class="four">V</div>
                    </div>
                    <h4>NO CARS !</h4>
                    <p>SORRY, YOU DON'T HAVE CARS IN RENT <br> PLEASE, RENT SOME.</p>
                    <%= link_to ' Go to Home', root_path, class: "fa fa-home btn-404-home" %>
                  </div>
                </div>
              </div>
            </div>
          </section>

        <% end %>
        </body>

car_rental/app/views/users/my_saved.html.erb
<body class="loader-active">
<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Favourite</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Car List Area Start ==-->
<section id="car-list-area" class="section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <% if @saved_cars.size > 0 %>
          <% @saved_cars.each do |car| %>
            <div class="row">
              <!-- Car List Content Start -->

              <div class="car-list-content">
                <!-- Single Car Start -->
                <div class="single-car-wrap">

                  <div class="row">
                    <!-- Single Car Thumbnail -->
                    <div class="col-lg-5">
                      <div class="car-list-thumb">
                      <!--car image-->
                      <% if car.image.attached? %>
                        <%= link_to image_tag(car.image), car_path(car) %>
                      <% end %>
                      </div>
                    </div>
                    <!-- Single Car Thumbnail -->

                    <!-- Single Car Info -->
                    <div class="col-lg-7">
                      <div class="display-table">
                        <div class="display-table-cell">
                          <div class="car-list-info">
                            <div class="row">
                              <div class="col-sm-8">
                                <h3><%= car.model %></h3>
                              </div>
                              <div class="col-sm-4">
                                <p class="rating">
                                  <% car.calculate_car_rate(car.id) %>
                                <div class="star-rating" data-score=<%= car.rank.ceil %>></div>
                                </p>
                              </div>
                            </div>
                            <h5><%= car.rent %>$ Rent /per a day</h5>
                            <p><%= car.discription %></p>
                            <ul class="car-info-list">
                              <li>Air Condition</li>
                              <li>Diesel</li>
                              <li>Auto</li>
                            </ul>

                            <!--to delete the recipe from the saved-->
                            <%= link_to "Unsave", saved_car_path(car), method: :delete, class: "rent-btn" %>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- Single Car info -->
                  </div>
                </div>
                <!-- Single Car End -->
              </div>

              <!-- Car List Content End -->
            </div>
            <br>
          <% end %>
          </div>
          <!-- Sidebar Area Start -->
          <div class="col-lg-4">
            <div class="sidebar-content-wrap m-t-50">
              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>For More Informations</h3>

                <div class="sidebar-body">
                  <p><i class="fa fa-mobile"></i> +8801816 277 243</p>
                  <p><i class="fa fa-clock-o"></i> Mon - Sat 8.00 - 18.00</p>
                </div>
              </div>
              <!-- Single Sidebar End -->

              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>Rental Tips</h3>

                <div class="sidebar-body">
                  <ul class="recent-tips">
                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service1-img.png", alt: "JSOFT") %></a>
                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>

                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service2-img.png", alt: "JSOFT") %></a>

                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>

                    <li class="single-recent-tips">
                      <div class="recent-tip-thum">
                        <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>
                      </div>
                      <div class="recent-tip-body">
                        <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                        <span class="date">February 5, 2018</span>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- Single Sidebar End -->

              <!-- Single Sidebar Start -->
              <div class="single-sidebar">
                <h3>Connect with Us</h3>

                <div class="sidebar-body">
                  <div class="social-icons text-center">
                    <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-behance"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                    <a href="#" target="_blank"><i class="fa fa-dribbble"></i></a>
                  </div>
                </div>
              </div>
              <!-- Single Sidebar End -->
            </div>
          </div>
          <!-- Sidebar Area End -->
          </div>

          </div>
          </section>
          <!--== Car List Area End ==-->


        <% else %>

          <section id="page-404-wrap" class="section-padding overlay">
            <div class="container">
              <div class="row">

                <div class="col-lg-12 text-center">
                  <div class="page-404-content">
                    <div class="number">
                      <div class="four">F</div>
                      <div class="zero">
                        <%= image_tag("404.png", alt: "JSOFT") %>
                      </div>
                      <div class="four">V</div>
                    </div>
                    <h4>NO CARS !</h4>
                    <p>SORRY, YOU DON'T HAVE CARS IN FAVOURITE <br> PLEASE, ADD SOME.</p>
                    <%= link_to ' Go to Home', root_path, class: "fa fa-home btn-404-home" %>
                  </div>
                </div>
              </div>
            </div>
          </section>

        <% end %>


        </body>




<script>
    $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        }
    });
</script>

car_rental/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Points:</strong>
  <%= @user.points %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>