car_rental/config/routes.rb
Rails.application.routes.draw do


  resources :total_rentals
  get 'manage_statistics/total_stat'
  get 'manage_statistics/car_stat'
  root 'welcome#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  get 'saved', to: 'users#my_saved'
  post 'save_car', to: 'users#add_cars_to_favourite'

#  post 'rent_car', to: 'users#add_cars_to_rent'

  get 'rented', to: 'users#my_rented'
  get 'rent_car', to: 'users#add_cars_to_rent'

  delete 'delete', to: 'rented_cars#admin_destroy'

  get 'search', to: 'cars#search'

  post 'rented_cars/new'

  get 'about', to: "welcome#about"
  get 'services', to: "welcome#services"
  get 'contact', to: "welcome#contact"
  get 'blog', to: "welcome#blog"
  get 'fqa', to: "welcome#fqa"
  # get 'rented', to: 'users#my_rented'

  resources :cars do
    resources :reviews
  end
  resources :rented_cars
  resources :users
  resources :saved_cars

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

car_rental/app/views/layouts/_footer.html.erb
<!--== Footer Area Start ==-->
<section id="footer-area">
  <!-- Footer Widget Start -->
  <div class="footer-widget-area">
    <div class="container">
      <div class="row">
        <!-- Single Footer Widget Start -->
        <div class="col-lg-4 col-md-6">
          <div class="single-footer-widget">
            <h2>About Us</h2>
            <div class="widget-body">
              <%= image_tag("logo.png", alt: "JSOFT") %>
              <p>Lorem ipsum dolored is a sit ameted consectetur adipisicing elit. Nobis magni assumenda distinctio debitis, eum fuga fugiat error reiciendis.</p>

              <div class="newsletter-area">
                <form action="#">
                  <input type="email" placeholder="Subscribe Our Newsletter">
                  <button type="submit" class="newsletter-btn"><i class="fa fa-send"></i></button>
                </form>
              </div>

            </div>
          </div>
        </div>
        <!-- Single Footer Widget End -->

        <!-- Single Footer Widget Start -->
        <div class="col-lg-4 col-md-6">
          <div class="single-footer-widget">
            <h2>Recent Posts</h2>
            <div class="widget-body">
              <ul class="recent-post">
                <li>
                  <a href="#">
                    Hello Bangladesh!
                    <i class="fa fa-long-arrow-right"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    Lorem ipsum dolor sit amet
                    <i class="fa fa-long-arrow-right"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    Hello Bangladesh!
                    <i class="fa fa-long-arrow-right"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    consectetur adipisicing elit?
                    <i class="fa fa-long-arrow-right"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Single Footer Widget End -->

        <!-- Single Footer Widget Start -->
        <div class="col-lg-4 col-md-6">
          <div class="single-footer-widget">
            <h2>get touch</h2>
            <div class="widget-body">
              <p>Lorem ipsum doloer sited amet, consectetur adipisicing elit. nibh auguea, scelerisque sed</p>

              <ul class="get-touch">
                <li><i class="fa fa-map-marker"></i> 800/8, Kazipara, Dhaka</li>
                <li><i class="fa fa-mobile"></i> +880 01 86 25 72 43</li>
                <li><i class="fa fa-envelope"></i> kazukamdu83@gmail.com</li>
              </ul>
              <a href="https://goo.gl/maps/b5mt45MCaPB2" class="map-show" target="_blank">Show Location</a>
            </div>
          </div>
        </div>
        <!-- Single Footer Widget End -->
      </div>
    </div>
  </div>
  <!-- Footer Widget End -->

  <!-- Footer Bottom Start -->
  <div class="footer-bottom-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer Bottom End -->
</section>
<!--== Footer Area End ==-->

<!--== Scroll Top Area Start ==-->
<div class="scroll-top">
  <%= image_tag("scroll-top.png", alt: "JSOFT") %>
</div>
<!--== Scroll Top Area End ==-->

car_rental/app/views/layouts/_header.html.erb
<!--== Header Area Start ==-->
<header id="header-area" class="fixed-top">
  <!--== Header Top Start ==-->
  <div id="header-top" class="d-none d-xl-block">
    <div class="container">
      <div class="row">
        <!--== Single HeaderTop Start ==-->
        <div class="col-lg-3 text-left">
          <i class="fa fa-map-marker"></i> 802/2, Mirpur, Dhaka
        </div>
        <!--== Single HeaderTop End ==-->

        <!--== Single HeaderTop Start ==-->
        <div class="col-lg-3 text-center">
          <i class="fa fa-mobile"></i> +1 800 345 678
        </div>
        <!--== Single HeaderTop End ==-->

        <!--== Single HeaderTop Start ==-->
        <div class="col-lg-3 text-center">
          <i class="fa fa-clock-o"></i> Mon-Fri 09.00 - 17.00
        </div>
        <!--== Single HeaderTop End ==-->

        <!--== Social Icons Start ==-->
        <div class="col-lg-3 text-right">
          <div class="header-social-icons">
            <a href="#"><i class="fa fa-behance"></i></a>
            <a href="#"><i class="fa fa-pinterest"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
        <!--== Social Icons End ==-->
      </div>
    </div>
  </div>
  <!--== Header Top End ==-->

  <!--== Header Bottom Start ==-->
  <div id="header-bottom">
    <div class="container">
      <div class="row">
        <!--== Logo Start ==-->
        <div class="col-lg-4">
          <a href="index.html" class="logo">
            <%=link_to image_tag("logo.png", alt: "JSOFT"),root_path %>
          </a>

          <%= form_tag('/search', :method => "get",
                       class: 'navbar-form navbar-left') do %>
            <div class="input-group">
              <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
              <select id="attribute" , name="attribute" , class="form-control">
                <option value="None" id="None">--Select--</option>
                <option value="Name" name="name">Model name</option>
                <option value="Year" name="year">Year</option>
                <option value="Price" name="price">Price</option>
              </select><br> <br>
              <div class="input-group-btn">
                <%= button_tag "submit", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
              </div>
            </div>
          <% end %>

        </div>
        <!--== Logo End ==-->

        <!--== Main Menu Start ==-->
        <div class="col-lg-8 d-none d-xl-block">
          <nav class="mainmenu alignright">
            <ul>
              <li><%= link_to 'Home', root_path %></li>


              <li class="active"><a href="#">Cars</a>
                <ul>
                  <li><%= link_to 'Cars', cars_path %></li>
                  <% if logged_in? %>
                    <li><%= link_to "Favourite", saved_path %></li>
                    <li><%= link_to "My Rents",rent_car_path%></li>
                    <% if current_user.admin? %>
                      <li><%= link_to "Rented Cars", rented_cars_path %></li>
                    <% end %>
                  <% end %>
                </ul>
              </li>

              <li><a href="index.html">Pages</a>
                <ul>
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Services", services_path %></li>
                  <li><%= link_to "FAQ", fqa_path %></li>
                </ul>
              </li>
              <li><%= link_to "Blog", blog_path %></li>

              <li><%= link_to "Contact", contact_path %></li>
              <% if logged_in? %>

                <% if current_user.admin? %>
                  <li><a href="#">Settings</a>
                    <ul>
                      <li><%= link_to 'Add new car', new_car_path %></li>
                      <li><%= link_to 'Statistics', {:controller=>"manage_statistics", :action=>"total_stat"}  %></li>
                    </ul>
                  </li>
                <% end %>

                <li><%= link_to 'Logout', logout_path, method: :delete %></li>

              <% else %>
                <li><%= link_to 'Login', login_path %></li>
              <% end %>

            </ul>
          </nav>
        </div>
        <!--== Main Menu End ==-->
      </div>
    </div>
  </div>
  <!--== Header Bottom End ==-->
</header>
<!--== Header Area End ==-->

car_rental/app/views/layouts/_preloader.html.erb
<!--== Preloader Area Start ==-->
<div class="preloader">
  <div class="preloader-spinner">
    <div class="loader-content">
      <%= image_tag("preloader.gif", alt: "JSOFT") %>
    </div>
  </div>
</div>
<!--== Preloader Area End ==-->

car_rental/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--=== Favicon ===-->
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
  <%= favicon_link_tag 'logo.png' %>


  <title>Car Rental</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <script src="jquery.raty.js"></script>

  <!--[if lt IE 9]>
  <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<%= render 'layouts/header' %>
<%= render 'layouts/preloader' %>
<%= yield %><br>
<%= render 'layouts/footer' %>
</body>
</html>