car_rental/config/routes.rb
Rails.application.routes.draw do


  resources :total_rentals
  get 'manage_statistics/total_stat'
  get 'manage_statistics/car_stat'
  root 'welcome#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  get 'saved', to: 'users#my_saved'
  post 'save_car', to: 'users#add_cars_to_favourite'

#  post 'rent_car', to: 'users#add_cars_to_rent'

  get 'rented', to: 'users#my_rented'
  get 'rent_car', to: 'users#add_cars_to_rent'

  delete 'delete', to: 'rented_cars#admin_destroy'

  get 'search', to: 'cars#search'

  post 'rented_cars/new'

  get 'about', to: "welcome#about"
  get 'services', to: "welcome#services"
  get 'contact', to: "welcome#contact"
  get 'blog', to: "welcome#blog"
  get 'fqa', to: "welcome#fqa"
  # get 'rented', to: 'users#my_rented'

  resources :cars do
    resources :reviews
  end
  resources :rented_cars
  resources :users
  resources :saved_cars

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

car_rental/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_car

  # GET /reviews
  # GET /reviews.json
  def index
    #@reviews = Review.all
    # logger.info "Car id = #{@car.id}"
    @reviews = Review.where(car_id: @car.id).order("created_at DESC")
  end

  # GET /reviews/1
  # GET /reviews/1.json


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.car_id = @car.id

    if @review.save
      redirect_to car_reviews_path(@car)
    else
      render 'new'
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @car, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to car_reviews_path(@car), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

  def set_car
    @car = Car.find(params[:car_id])
  end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit( :rank, :content)
    end
end

car_rental/app/helpers/reviews_helper.rb
module ReviewsHelper
end

car_rental/app/views/reviews/_form.html.erb
<%= form_for([@car, @review]) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--  <div class="field">-->
  <%#= form.label :user_id %>
  <%#= form.text_field :user_id %>
  <!--  </div>-->
  <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-5">

      <% if @car.image.attached? %>
        <div class="recent-tip-thum">
          <a href="#"><%= image_tag(@car.image) %></a>
          <h3><%=@car.model %></h3>
        </div>
      <% end %>
      <br>
      <br>
    </div>
  </div>
  <!--  <div class="field">-->
  <%#= form.label :car_id %>
  <%#= form.text_field :car_id %>
  <!--  </div>-->
  <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-4">
      <div class="field">
        <%#= form.label :rank %>
        <div id="star-rating">
        </div>
      </div>
      <br>
    </div>
  </div>
  <div class="field">
    <%= form.text_area(:content, size: '100x10', placeholder: "
    Write Your Feedback Here....", autofocus: true) %>
  </div>


  <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-4">
      <div class="actions input-submit">
        <%= form.submit 'Commit', :class => "rent-btn" %>
      </div>
    </div>
  </div>
<% end %>

<!--<script>-->
<!--    $('.star-rating').raty({-->
<!--        path: '/assets/',-->
<!--        click: true,-->
<!--        hints: ['bad', 'poor', 'regular', 'good', 'gorgeous'],-->
<!--        score: function() {-->
<!--            return $(this).attr('data-score');-->
<!--        }-->
<!--    });-->
<!--</script>-->

<script>
    $('#star-rating').raty({
        path: '/assets/',
        hints: ['bad', 'poor', 'regular', 'good', 'gorgeous'],
        scoreName: 'review[rank]'
    });
</script>

car_rental/app/views/reviews/edit.html.erb
<body class="loader-active">

<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Edit Your Review</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Login Page Content Start ==-->
<section id="lgoin-page-wrap" class="section-padding">
  <div class="container ">

    <div class="row">
      <div class="col-md-2"></div>

      <div class=" col-md-9">
        <div class="jumbotron">
          <%= render 'form', review: @review %>
        </div>
      </div>
    </div>
  </div>
</section>
<!--== Login Page Content End ==-->

</body>

car_rental/app/views/reviews/index.html.erb
<body class="loader-active">

<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Reviews</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<br>
<br>

<p id="notice"><%= notice %></p>


<% @reviews.each do |review| %>
  <% @user = User.find(review.user_id) %>
  <% @car = Car.find(review.car_id) %>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-7 jumbotron">

      <div class="row ">
        <div class="col-md-1">
          <div class="recent-tip-thum">
            <a href="#"><%= image_tag("avatar.png", alt: "JSOFT") %></a>
          </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-6 ">
          <br>
          <h6><%= @user.user_name %></h6>
          <div class="star-rating" data-score=<%= review.rank %>></div>
          <br>
          <%= review.content %>
        </div>

        <div class="col-md-3 "></div>
        <div class="col-md-1 ">
          <!--drop down list-->
          <div class=" float-right">
            <div class="btn-group">
              <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-option-horizontal"></span>
              </button>
              <div class="dropdown-menu">
                <%= link_to "Edit", edit_car_review_path(@car, review), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Delete", car_review_path(@car, review), method: :delete,
                            data: {confirm: "Are you sure you want to delete the review?"},
                            class: "dropdown-item" %>
              </div>
            </div>
          </div>
          <!--end of the drop down list-->
        </div>
      </div>

      <hr>
      <div class="meta-details">
        <small>
          created from: <%= time_ago_in_words(review.created_at) %> ago,
          last updated: <%= time_ago_in_words(review.updated_at) %> ago</small>
      </div>
    </div>

    <div class="col-md-2"></div>
  </div>


<% end %>


<br>

<%#= link_to 'New Review', new_review_path %>
</body>

<script>
    $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        }
    });
</script>

car_rental/app/views/reviews/new.html.erb
<body class="loader-active">

<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Your Review</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Login Page Content Start ==-->
<section id="lgoin-page-wrap" class="section-padding">
  <div class="container ">

    <div class="row">
      <div class="col-md-2"></div>

      <div class=" col-md-9">
        <div class="jumbotron">
          <%= render 'form', review: @review %>
        </div>
      </div>
    </div>
  </div>
</section>
<!--== Login Page Content End ==-->

</body>

car_rental/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Car:</strong>
  <%= @review.car_id %>
</p>

<p>
  <strong>Rank:</strong>
  <div class="star-rating" data-score= <%= @review.rank %> ></div>
  <%#= @review.rank %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>


<script>
    $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        }
    });
</script>