car_rental/config/routes.rb
Rails.application.routes.draw do


  resources :total_rentals
  get 'manage_statistics/total_stat'
  get 'manage_statistics/car_stat'
  root 'welcome#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  get 'saved', to: 'users#my_saved'
  post 'save_car', to: 'users#add_cars_to_favourite'

#  post 'rent_car', to: 'users#add_cars_to_rent'

  get 'rented', to: 'users#my_rented'
  get 'rent_car', to: 'users#add_cars_to_rent'

  delete 'delete', to: 'rented_cars#admin_destroy'

  get 'search', to: 'cars#search'

  post 'rented_cars/new'

  get 'about', to: "welcome#about"
  get 'services', to: "welcome#services"
  get 'contact', to: "welcome#contact"
  get 'blog', to: "welcome#blog"
  get 'fqa', to: "welcome#fqa"
  # get 'rented', to: 'users#my_rented'

  resources :cars do
    resources :reviews
  end
  resources :rented_cars
  resources :users
  resources :saved_cars

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

car_rental/app/models/car.rb
class Car < ApplicationRecord
	# has_many :rentals, dependent: :destroy
	has_many :reviews, dependent: :destroy
	has_many :rented_cars, dependent: :destroy
	has_many :total_rentals
	has_one_attached :image

	#has_many :users, through: :rented_cars

	# the cars that the user saved
	has_many :user_cars
	has_many :users, through: :user_cars

	# the cars that the user rented
	# has_many :user_rents
	# has_many :users, through: :user_rents

	validates :model, presence: true, length: { minimum: 3, maximum: 25 }
	validates :rent, presence: true, numericality: {greater_than: 0 }
	validates :productionYear, presence: true, numericality: {greater_than: 1990 }
	validates :seats, presence: true, numericality: {greater_than: 0 }
	validates :discription, presence: true, length: { minimum: 10}
	validates :rank, presence: true, numericality: {greater_than: -1.0, smaller_than: 6.0 }
	validate :check_image_existence


	def calculate_car_rate(car_id)
		# if count is < 1 means that the count is zero so it isn't saved
		car_reviews = reviews.where(car_id: car_id)
		i = 0
		reviews_counter = 0
		valid_reviews = 0
		# logger.info "reviews_counter: #{car_reviews.length}"

		if car_reviews.length > 0
			while i < car_reviews.length
				#logger.info "rank no.#{i} =: #{car_reviews[i].rank}"
				reviews_counter += car_reviews[i].rank

				if car_reviews[i].rank != 0
					valid_reviews += 1
				end

				i = i + 1
			end

			#logger.info "valid_reviews =: #{valid_reviews}"
			# logger.info "reviews_counter =: #{reviews_counter}"
			# calculate avg
			reviews_counter = (reviews_counter / valid_reviews)
		end
		car = Car.find(car_id)
		car.rank = reviews_counter
		car.save
	end



	private
	def check_image_existence
		if image.attached? == false
			errors.add(:image, "is required.")
		end
	end
end

car_rental/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.paginate(page: params[:page], per_page: 12)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    # @reviews = Review.where(car_id: @car.id).order("created_at DESC")
    #
    # if @reviews.blank?
    #   @avg_review = 0
    # else
    #   @avg_review = ceil(@reviews.average(:rank))
    # end

  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    if params[:search].blank?
      redirect_to(cars_url, alert: "Empty field!") and return
    elsif params[:attribute] == "Name"
      @cars= Car.where("model LIKE ?", "%" + params[:search] + "%" )
    elsif params[:attribute] == "Year"
      @cars= Car.where("productionYear = ?",params[:search])
    elsif params[:attribute] == "Price"
      @cars= Car.where("rent = ?",params[:search])
    elsif params[:attribute] == "None"
      redirect_to(cars_url, alert: "Empty field!") and return
    end
  end



  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:model, :rank, :rent, :automatic, :airconditioned, :productionYear, :seats, :discription, :image)
    end

    def require_admin
      if logged_in? and !current_user.admin?
        #flash[:danger] = 'Only admin users can perform that action'
        redirect_to root_path
      end
    end

end

car_rental/app/helpers/cars_helper.rb
module CarsHelper
end

car_rental/app/views/cars/_form.html.erb
<%= render 'shared/errors', object:@car %>

<%= form_with(model: car, local: true) do |form| %>

  <div class="field">
    <%= form.file_field :image %>
  </div>



  <div class="field">
    <%= form.text_field :model , class: "form-control",  autofocus: true, placeholder: "Model..."%>
  </div>

  <div class="field">
    <%= form.number_field :productionYear,class: "form-control",  autofocus: true, placeholder: "Production Year..." %>
  </div>

  <div class="field">
    <%= form.text_field :discription,class: "form-control",  autofocus: true, placeholder: "Description..." %>
  </div>

<!--  <div class="field">-->
    <%#= form.text_field :rank,class: "form-control",  autofocus: true, placeholder: "Rank..." %>
<!--    <div id="star-rating"></div>-->
<!--  </div>-->

  <div class="field">
    <%= form.text_area :rent,class: "form-control",  autofocus: true, placeholder: "RentedCar..." %>
  </div>

  <div class="field">
    <%= form.number_field :seats,class:"form-control",  autofocus: true, placeholder: "Number of seats..." %>
  </div>

  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-4">
      <div class="field">
        <%= form.label :aircondition %>
        <%= form.check_box :airconditioned ,class: "form-control"%>
      </div>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-4">
      <div class="field">
        <%= form.label :automatic %>
        <%= form.check_box :automatic, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-6">
      <div class="log-btn">
        <%= form.submit "Done",class: "btn" %>
      </div>
    </div>
  </div>

<% end %>


<!--<script>-->
<!--    $('#star-rating').raty({-->
<!--        path: '/assets/',-->
<!--        hints: ['bad', 'poor', 'regular', 'good', 'gorgeous'],-->
<!--        scoreName: 'car[ranking]'-->
<!--    });-->
<!--</script>-->

car_rental/app/views/cars/edit.html.erb
<body class="loader-active">

<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Edit Car</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Login Page Content Start ==-->
<section id="lgoin-page-wrap" class="section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-8 m-auto">
        <div class="login-page-content">
          <div class="login-form">
            <%= render 'form', car: @car %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--== Login Page Content End ==-->
</body>

car_rental/app/views/cars/index.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
  <title>Catalogue</title>
</head>

<body class="loader-active">

<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Our Cars</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>We are here for you.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Car List Area Start ==-->
<section id="car-list-area" class="section-padding">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <% i = 0 %>
    <% while i < @cars.length %>
      <div class="row">
        <!-- Car List Content Start -->
        <div class="col-lg-12">
          <div class="car-list-content">
            <div class="row">
              <!-- Single Car Start -->
              <div class="col-lg-6 col-md-6">
                <div class="single-car-wrap">
                  <div class="car-list-thumb ">
                    <% if @cars[i].image.attached? %>
                      <%= image_tag(@cars[i].image) %>
                    <% end %>

                  </div>
                  <br>
                  <div class="car-list-info without-bar">
                    <br>
                    <div class="row">
                      <div class="col-sm-9">
                        <h2><%= @cars[i].model %></h2>
                      </div>
                      <div class="col-sm-3">
                        <p class="rating">
                          <%@cars[i].calculate_car_rate(@cars[i].id)%>
                          <div class="star-rating" data-score=<%= @cars[i].rank.ceil %>></div>
                        </p>
                      </div>
                    </div>
                    <h5><%= @cars[i].rent %>$ Rent /per a day</h5>
                    <p><%= @cars[i].discription %></p>
                    <ul class="car-info-list">
                      <li>AC</li>
                      <li>Auto</li>
                      <li>Diesel</li>
                    </ul>

                    <% if @cars[i].airconditioned %>

                    <% else %>

                    <% end %>

                    <% if @cars[i].automatic %>
                    <% else %>

                    <% end %>
                    <div class="row">
                      <div class="col-sm-2">
                        <%= link_to 'Details', @cars[i], class: "rent-btn" %>
                      </div>
                      <!--                      <div class="col-sm-1"></div>-->
                      <% if logged_in? %>
                        <div class="col-sm-2">
                          <% if current_user.car_not_saved?(@cars[i].id) %>
                            <%= link_to "Save", save_car_path(user: current_user, savedcar: @cars[i]), class: "rent-btn", method: :post %>
                          <% else %>
                            <%= link_to "Unsave", saved_car_path(@cars[i]), method: :delete, class: "rent-btn" %>
                          <% end %>
                        </div>
                        <div class="col-sm-2">
                          <% if current_user.car_not_rented?(@cars[i].id) %>
                            <!-- saving the car in the browser session hash-->
                            <%logger.info "car id =: #{@cars[i].id}" %>
                            <%= link_to "Rent", rented_cars_new_path(:car_id =>@cars[i].id),:method => :post, class: "rent-btn" %>
                          <% else %>
                            <%= link_to "Cancel", rented_car_path(@cars[i]), method: :delete, class: "rent-btn" %>
                          <% end %>
                        </div>


                      <% end %>
                      <!--                      <div class="col-sm-1"></div>-->
                      <% if logged_in? && current_user.admin? %>
                        <div class="col-sm-2">
                          <%= link_to 'Edit', edit_car_path(@cars[i]), class: "rent-btn" %>
                        </div>
                        <!--                        <div class="col-sm-1"></div>-->
                        <div class="col-sm-2">
                          <%= link_to 'Delete', @cars[i], method: :delete, data: {confirm: 'Are you sure?'}, class: "rent-btn" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <% i += 1 %>
              <!-- Single Car End -->
              <% if i < @cars.length %>
                <!-- Single Car Start -->
                <div class="col-lg-6 col-md-6">
                  <div class="single-car-wrap">
                    <div class="car-list-thumb">
                      <% if @cars[i].image.attached? %>
                        <%= image_tag(@cars[i].image) %>
                      <% end %>

                    </div>
                    <br>
                    <div class="car-list-info without-bar">
                      <br>
                      <div class="row">
                        <div class="col-sm-9">
                          <h2><%= @cars[i].model %></h2>
                        </div>
                        <div class="col-sm-3">
                          <p class="rating">
                            <%@cars[i].calculate_car_rate(@cars[i].id)%>
                            <div class="star-rating" data-score=<%= @cars[i].rank.ceil %>></div>
                          </p>
                        </div>
                      </div>
                      <h5><%= @cars[i].rent %>$ Rent /per a day</h5>
                      <p><%= @cars[i].discription %></p>
                      <ul class="car-info-list">
                        <li>AC</li>
                        <li>Auto</li>
                        <li>Diesel</li>
                      </ul>
                      <% if @cars[i].airconditioned %>

                      <% else %>

                      <% end %>

                      <% if @cars[i].automatic %>
                      <% else %>

                      <% end %>
                      <div class="row">
                        <div class="col-sm-2">
                          <%= link_to 'Details', @cars[i], class: "rent-btn" %>
                        </div>
                        <!--                        <div class="col-sm-1"></div>-->
                        <% if logged_in? %>
                          <div class="col-sm-2">
                            <% if current_user.car_not_saved?(@cars[i].id) %>
                              <%= link_to "Save", save_car_path(user: current_user, savedcar: @cars[i]), class: "rent-btn", method: :post %>
                            <% else %>
                              <%= link_to "Unsave", saved_car_path(@cars[i]), method: :delete, class: "rent-btn" %>
                            <% end %>
                          </div>

                          <div class="col-sm-2">
                            <% if current_user.car_not_rented?(@cars[i].id) %>
                              <!-- saving the car in the browser session hash-->
                              <%#logger.info "car id =: #{@cars[i].id}" %>
                              <%= link_to "Rent", rented_cars_new_path(:car_id =>@cars[i].id),:method => :post, class: "rent-btn" %>
                              <%#logger.info "car id =: #{session[:rentedcar_id]}" %>
                            <% else %>
                              <%= link_to "Cancel", rented_car_path(@cars[i]), method: :delete, class: "rent-btn" %>
                            <% end %>
                          </div>
                        <% end %>
                        <!--                        <div class="col-sm-1"></div>-->
                        <% if logged_in? && current_user.admin? %>
                          <div class="col-sm-2">
                            <%= link_to 'Edit', edit_car_path(@cars[i]), class: "rent-btn" %>
                          </div>
                          <!--                          <div class="col-sm-1"></div>-->
                          <div class="col-sm-2">
                            <%= link_to 'Delete', @cars[i], method: :delete, data: {confirm: 'Are you sure?'}, class: "rent-btn" %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Single Car End -->
              <% end %>
              <% i += 1 %>
    <% end %>
    </div>
    </div>

    <!-- Page Pagination Start -->
    <div class="page-pagi">
      <nav aria-label="Page navigation example">
        <div class="row">
          <div class="col-sm-4"></div>
          <div class="col-sm-4">
            <%= will_paginate %>
          </div>
          <div class="col-sm-4"></div>
        </div>
      </nav>
    </div>
    <!-- Page Pagination End -->
    </div>
    <!-- Car List Content End -->
    </div>
  </div>
</section>
<!--== Car List Area End ==-->

</body>

</html>



<script>
    $('.star-rating').raty({
        path: '/assets/',
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        }
    });
</script>

car_rental/app/views/cars/search.html.erb
<h1>Search Results</h1>

<section id="car-list-area" class="section-padding">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <% i = 0 %>
    <% while i < @cars.length %>
      <div class="row">
        <!-- Car List Content Start -->
        <div class="col-lg-12">
          <div class="car-list-content">
            <div class="row">
              <!-- Single Car Start -->
              <div class="col-lg-6 col-md-6">
                <div class="single-car-wrap">
                  <div class="car-list-thumb ">
                    <% if @cars[i].image.attached? %>
                      <%=image_tag(@cars[i].image) %>
                    <%end %>
                  </div>
                  <br>
                  <div class="car-list-info without-bar">
                    <h2><%= @cars[i].model %></h2>
                    <h5><%= @cars[i].rent %>$ Rent /per a day</h5>
                    <p><%= @cars[i].discription %></p>
                    <ul class="car-info-list">
                      <li>AC</li>
                      <li>Auto</li>
                      <li>Diesel</li>
                    </ul>
                    <p class="rating">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star unmark"></i>
                    </p>
                    <% if @cars[i].airconditioned %>

                    <% else %>

                    <% end %>

                    <% if @cars[i].automatic %>
                    <% else %>

                    <% end %>
                    <div class="row">
                      <div class="col-sm-2">
                        <%= link_to 'Details', @cars[i], class: "rent-btn" %>
                      </div>
                      <div class="col-sm-1"></div>
                      <%if logged_in?%>
                        <div class="col-sm-2">
                          <% if current_user.car_not_saved?(@cars[i].id) %>
                            <%= link_to "Save", save_car_path(user: current_user, car: @cars[i]), class: "rent-btn", method: :post %>
                          <% else %>
                            <%= link_to "Unsave", favourite_path(@cars[i]), method: :delete, class: "rent-btn" %>
                          <% end %>
                        </div>
                      <%end %>
                      <div class="col-sm-1"></div>
                      <%if logged_in? && current_user.admin?%>
                        <div class="col-sm-2">
                          <%= link_to 'Edit', edit_car_path(@cars[i]), class: "rent-btn" %>
                        </div>
                        <div class="col-sm-1"></div>
                        <div class="col-sm-2">
                          <%= link_to 'Delete', @cars[i], method: :delete, data: {confirm: 'Are you sure?'}, class: "rent-btn" %>
                        </div>
                      <%end %>
                    </div>
                  </div>
                </div>
              </div>
              <% i += 1 %>
              <!-- Single Car End -->
              <% if i < @cars.length %>
                <!-- Single Car Start -->
                <div class="col-lg-6 col-md-6">
                  <div class="single-car-wrap">
                    <div class="car-list-thumb">
                      <% if @cars[i].image.attached? %>
                        <%=image_tag(@cars[i].image) %>
                      <%end %>
                    </div>
                    <br>
                    <div class="car-list-info without-bar">
                      <h2><%= @cars[i].model %></h2>
                      <h5><%= @cars[i].rent %>$ Rent /per a day</h5>
                      <p><%= @cars[i].discription %></p>
                      <ul class="car-info-list">
                        <li>AC</li>
                        <li>Auto</li>
                        <li>Diesel</li>
                      </ul>
                      <p class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star unmark"></i>
                      </p>
                      <% if @cars[i].airconditioned %>

                      <% else %>

                      <% end %>

                      <% if @cars[i].automatic %>
                      <% else %>

                      <% end %>
                      <div class="row">
                        <div class="col-sm-2">
                          <%= link_to 'Details', @cars[i], class: "rent-btn" %>
                        </div>
                        <div class="col-sm-1"></div>
                        <%if logged_in?%>
                          <div class="col-sm-2">
                            <% if current_user.car_not_saved?(@cars[i].id) %>
                              <%= link_to "Save", save_car_path(user: current_user, car: @cars[i]), class: "rent-btn", method: :post %>
                            <% else %>
                              <%= link_to "Unsave", favourite_path(@cars[i]), method: :delete,
                                          data: {confirm: "Are you sure?"}, class: "rent-btn" %>
                            <% end %>
                          </div>
                        <%end %>
                        <div class="col-sm-1"></div>
                        <%if logged_in? && current_user.admin?%>
                          <div class="col-sm-2">
                            <%= link_to 'Edit', edit_car_path(@cars[i]), class: "rent-btn" %>
                          </div>
                          <div class="col-sm-1"></div>
                          <div class="col-sm-2">
                            <%= link_to 'Delete', @cars[i], method: :delete, data: {confirm: 'Are you sure?'}, class: "rent-btn" %>
                          </div>
                        <%end %>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Single Car End -->
              <% end %>
              <% i += 1 %>
    <% end %>
    </div>
    </div>

    </div>
    <!-- Car List Content End -->
    </div>
  </div>
</section>

car_rental/app/views/cars/show.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">

<body class="loader-active">
<p id="notice"><%= notice %></p>

<!--== Page Title Area Start ==-->
<section id="page-title-area" class="section-padding overlay">
  <div class="container">
    <div class="row">
      <!-- Page Title Start -->
      <div class="col-lg-12">
        <div class="section-title  text-center">
          <h2>Our Cars</h2>
          <span class="title-line"><i class="fa fa-car"></i></span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
      <!-- Page Title End -->
    </div>
  </div>
</section>
<!--== Page Title Area End ==-->

<!--== Car List Area Start ==-->
<section id="car-list-area" class="section-padding">
  <div class="container">
    <div class="row">
      <!-- Car List Content Start -->
      <div class="col-lg-8">
        <div class="car-details-content">
          <h2><%= @car.model %> <span class="price">Rent: <b><%= @car.rent %>$</b></span></h2>
          <div>
            <div class="single-car-preview">
              <% if @car.image.attached? %>
                <%= image_tag(@car.image) %>
              <% end %>
            </div>
          </div>
          <div class="car-details-info">
            <h4>Additional Info</h4>
            <p><%= @car.discription %></p>

            <div class="technical-info">
              <div class="row">
                <div class="col-lg-6">
                  <div class="tech-info-table">
                    <table class="table table-bordered">
                      <tr>
                        <th>Production year</th>
                        <td><%= @car.productionYear %></td>
                      </tr>
                      <tr>
                        <th>Auto/Manual</th>
                        <td><%= @car.automatic %></td>
                      </tr>
                      <tr>
                        <th>Seats</th>
                        <td><%= @car.seats %></td>
                      </tr>
                      <tr>
                        <th>Rank</th>
                        <td><%= @car.rank %></td>
                      </tr>
                    </table>
                  </div>
                </div>

                <div class="col-lg-6">
                  <div class="tech-info-list">
                    <ul>
                      <li>ABS</li>
                      <li>Air Bags</li>
                      <li>Bluetooth</li>
                      <li>Car Kit</li>
                      <li>GPS</li>
                      <li>Music</li>
                      <li>Bluetooth</li>
                      <li>ABS</li>
                      <li>GPS</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-9">
                <div class="review-area">
                  <h2>Review Our {<%= @car.model %>}</h2>
                  <div class="review-star">
                    <p class="rating">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star "></i>
                      <i class="fa fa-star "></i>
                    </p>
                  </div>


                  <div class="review-form">
                    <form action="index.html">

                      <div class="input-submit">
                        <%= link_to 'Your Review', new_car_review_path(@car), class: "rent-btn" %>
                        <%= link_to 'All Reviews', car_reviews_path(@car), class: "rent-btn" %>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="col-md-3"></div>
              </div>


            </div>
          </div>
        </div>
      </div>
      <!-- Car List Content End -->

      <!-- Sidebar Area Start -->
      <div class="col-lg-4">
        <div class="sidebar-content-wrap m-t-50">
          <!-- Single Sidebar Start -->
          <div class="single-sidebar">
            <h3>For More Informations</h3>

            <div class="sidebar-body">
              <p><i class="fa fa-mobile"></i> +8801816 277 243</p>
              <p><i class="fa fa-clock-o"></i> Mon - Sat 8.00 - 18.00</p>
            </div>
          </div>
          <!-- Single Sidebar End -->

          <!-- Single Sidebar Start -->
          <div class="single-sidebar">
            <h3>Rental Tips</h3>

            <div class="sidebar-body">
              <ul class="recent-tips">
                <li class="single-recent-tips">
                  <div class="recent-tip-thum">
                    <a href="#"><%= image_tag("we-do/service1-img.png", alt: "JSOFT") %></a>
                  </div>
                  <div class="recent-tip-body">
                    <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                    <span class="date">February 5, 2018</span>
                  </div>
                </li>

                <li class="single-recent-tips">
                  <div class="recent-tip-thum">
                    <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>
                  </div>
                  <div class="recent-tip-body">
                    <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                    <span class="date">February 5, 2018</span>
                  </div>
                </li>

                <li class="single-recent-tips">
                  <div class="recent-tip-thum">

                    <a href="#"><%= image_tag("we-do/service2-img.png", alt: "JSOFT") %></a>
                  </div>
                  <div class="recent-tip-body">
                    <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                    <span class="date">February 5, 2018</span>
                  </div>
                </li>

                <li class="single-recent-tips">
                  <div class="recent-tip-thum">
                    <a href="#"><%= image_tag("we-do/service3-img.png", alt: "JSOFT") %></a>
                  </div>
                  <div class="recent-tip-body">
                    <h4><a href="#">How to Enjoy Losses Angeles Car Rentals</a></h4>
                    <span class="date">February 5, 2018</span>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <!-- Single Sidebar End -->

          <!-- Single Sidebar Start -->
          <div class="single-sidebar">
            <h3>Connect with Us</h3>

            <div class="sidebar-body">
              <div class="social-icons text-center">
                <%= social_share_button_tag(@car.model) %>
              </div>
            </div>
          </div>
          <!-- Single Sidebar End -->
        </div>
      </div>
      <!-- Sidebar Area End -->
    </div>
  </div>
</section>
<!--== Car List Area End ==-->


</body>

</html>